apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3" # adjust as needed
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
      metrics:
        enabled: true
