apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s # adjust as needed
  retryInterval: 1m0s
  timeout: 2m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  path: ./base/external-dns/
  prune: true