apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 8.7.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  install:
    createNamespace: true
  values:
    configuration:
      provider: azure
      plugins:
        - velero/velero-plugin-for-microsoft-azure:v1.7.0 # Required plugin for Azure
      
      # Backup Storage Location (Blob Storage)
      backupStorageLocation:
        name: azure
        bucket: "velero-backups" # e.g., velero-backups-12345
        config:
          resourceGroup: "rg-aks-kubenet-demo"
          storageAccount: "kushalvelerobackup"
          subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
          cloudName: AzurePublicCloud

      # Volume Snapshot Location (AKS Node Resource Group)
      volumeSnapshotLocation:
        name: azure-default
        config:
          # This RG is typically the AKS Node Resource Group (MC_...)
          resourceGroup: "rg-aks-kubenet-demo"
          subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
          apiTimeout: "5m"

    serviceAccount:
      server:
        create: true
        name: velero # Velero's default Service Account name
        annotations:
          azure.workload.identity/client-id: "5bae3c20-8ea1-4a5c-beaf-83ae2b512e1b" # <-- Use your Terraform UAMI Client ID
          azure.workload.identity/tenant-id: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"

    podLabels:
      azure.workload.identity/use: "true"
      
    credentials:
      useSecret: false