apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  install:
    createNamespace: true
  values: 
    configuration:
      plugins:
        - velero/velero-plugin-for-microsoft-azure:v1.7.0 # Required plugin for Azure
      
      # Backup Storage Location (Blob Storage)
      backupStorageLocation:
        - name: azure
          provider: azure
          bucket: "velero-backups" # e.g., velero-backups-12345
          default: false
          config:
            useAAD: true
            resourceGroup: "rg-aks-kubenet-demo"
            storageAccount: "kushalvelerobackup"
            subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
            cloudName: AzurePublicCloud

      # Volume Snapshot Location (AKS Node Resource Group)
      volumeSnapshotLocations:
        - name: azure-default
          provider: azure
          config:
            # This RG is typically the AKS Node Resource Group (MC_...)
            resourceGroup: "MC_rg-aks-kubenet-demo_aks-kubenet-cluster_eastus"
            subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
            apiTimeout: "5m"

    serviceAccount:
      server:
        create: true
        name: velero # Velero's default Service Account name
        annotations:
          azure.workload.identity/client-id: "c7ebe9d3-8fb4-405f-b158-945236b96adc" # <-- Use your Terraform UAMI Client ID
          azure.workload.identity/tenant-id: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"
        labels:
          azure.workload.identity/use: "true"
      
    credentials:
      useSecret: false

    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.13.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # kubectl:
    #   image:
    #     repository: bitnami/kubectl
    #   resources:
    #     limits:
    #       cpu: 128m
    #     requests:
    #       cpu: 50m
    #       memory: 64Mi

    image:
      repository: velero/velero
      tag: v1.16.2
      pullPolicy: IfNotPresent

    podLabels:
      app: velero
      azure.workload.identity/use: "true"