apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0  # pick latest from Bitnami repo
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: azure
    txtOwnerId: aks-externaldns
    policy: sync
    domainFilters:
      - internal.example.com
    sources:
      - service
      - ingress

    azure:
      tenantId: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"
      subscriptionId: "5c29cf98c-ebc4-49e6-bc42-a01527606175"
      resourceGroup: "rg-aks-kubenet-demo"
      useManagedIdentityExtension: true
      userAssignedIdentityID: "5fe7709d-f82c-4f4a-8d8f-1923a2057ae6"
      azureConfigFile: ""
      cloud: "AzurePublicCloud"
    secretConfiguration:
      enabled: true
      mountPath: "/etc/kubernetes/"
      data:
        azure.json: |
          {
            "tenantId": "6f818e3d-ede0-4045-a285-0a6c77b4cabb",
            "subscriptionId": "c29cf98c-ebc4-49e6-bc42-a01527606175",
            "resourceGroup": "rg-aks-kubenet-demo",
            "useManagedIdentityExtension": true,
            "userAssignedIdentityID": "5fe7709d-f82c-4f4a-8d8f-1923a2057ae6",
            "cloud": "AzurePublicCloud"
          }
    podLabels:
      app: external-dns
    logLevel: info