apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0  # pick latest from Bitnami repo
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: azure
    txtOwnerId: aks-externaldns
    policy: sync
    domainFilters:
      - internal.example.com
    sources:
      - service
      - ingress

    azure:
      useManagedIdentityExtension: false
      userAssignedIdentityClientID: "9937d1fe-25c8-4839-9afe-27009ca98fb7"
      resourceGroup: "rg-aks-kubenet-demo"
      subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
      tenantId: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"
      useworkloadIdentityExtension: true
      config: ""
        
    secretConfiguration:
      enabled: true
      mountPath: "/etc/kubernetes/"
      data:
        azure.json: |
          {
            "subscriptionId": "c29cf98c-ebc4-49e6-bc42-a01527606175",
            "resourceGroup": "rg-aks-kubenet-demo",
            "useworkloadIdentityExtension": true
          }


    podLabels:
      app: external-dns
      azure.workload.identity/use: "true"
    logLevel: info

    serviceAccount:
      name: external-dns
      annotations:
        azure.workload.identity/client-id: "9937d1fe-25c8-4839-9afe-27009ca98fb7"
        azure.workload.identity/tenant-id: 6f818e3d-ede0-4045-a285-0a6c77b4cabb