apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: azure
    txtOwnerId: aks-externaldns
    policy: sync
    domainFilters:
      - internal.example.com
    sources:
      - service
      - ingress

    extraArgs:
      - --azure-resource-group=rg-aks-kubenet-demo
      - --azure-subscription-id=c29cf98c-ebc4-49e6-bc42-a01527606175
      - --azure-user-assigned-identity-client-id=671e3865-b6fe-4845-a12b-0843d73930fb

    azure:
      userAssignedIdentityClientID: "671e3865-b6fe-4845-a12b-0843d73930fb"
      resourceGroup: "rg-aks-kubenet-demo"
      subscriptionId: "c29cf98c-ebc4-49e6-bc42-a01527606175"
      tenantId: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"
      config: ""

    serviceAccount:
      name: external-dns
      annotations:
        azure.workload.identity/client-id: "671e3865-b6fe-4845-a12b-0843d73930fb"

    logLevel: info

        azure.workload.identity/client-id: "671e3865-b6fe-4845-a12b-0843d73930fb"