apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0  # pick latest from Bitnami repo
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: azure
    txtOwnerId: aks-externaldns
    policy: sync
    domainFilters:
      - internal.example.com
    sources:
      - service
      - ingress

    extraEnvVars:
      - name: AZURE_TENANT_ID
        value: "6f818e3d-ede0-4045-a285-0a6c77b4cabb"
      - name: AZURE_SUBSCRIPTION_ID
        value: "5c29cf98c-ebc4-49e6-bc42-a01527606175"
      - name: AZURE_RESOURCE_GROUP
        value: "rg-aks-kubenet-demo"
      - name: AZURE_CLOUD
        value: "AzurePublicCloud"
      - name: AZURE_USE_MANAGED_IDENTITY_EXTENSION
        value: "true"
      - name: AZURE_USER_ASSIGNED_IDENTITY_CLIENT_ID
        value: "26cab066-1b8b-4cfd-bf03-acf2fccb4641"

    azure:
      useworkloadIdentityExtension: true

        
    secretConfiguration:
      enabled: true
      mountPath: "/etc/kubernetes/"
      data:
        azure.json: |
          {
            "tenantId": "6f818e3d-ede0-4045-a285-0a6c77b4cabb",
            "subscriptionId": "c29cf98c-ebc4-49e6-bc42-a01527606175",
            "resourceGroup": "rg-aks-kubenet-demo",
            "userAssignedIdentityID": "26cab066-1b8b-4cfd-bf03-acf2fccb4641",
            "useworkloadIdentityExtension": true,
            "cloud": "AzurePublicCloud"
          }
    podLabels:
      app: external-dns
    logLevel: info

    serviceAccount:
      name: external-dns
      annotations:
        azure.workload.identity/client-id: "26cab066-1b8b-4cfd-bf03-acf2fccb4641"