apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    azure.workload.identity/client-id: 671e3865-b6fe-4845-a12b-0843d73930fb  # <-- clientId of externaldns-identity
    azure.workload.identity/tenant-id: 6f818e3d-ede0-4045-a285-0a6c77b4cabb